trigger:
- main

variables:
  variable1: 'one'

pool:
  name: Default
  # vmImage: 'ubuntu-latest'

steps:
- script: echo "Hello, world!"
  displayName: 'Run a one-line script'

- script: |
    echo "Template expression: ${{ variables.variable1 }}"
    echo "Macro variable: $(variable1)"
    echo "Runtime expression: $[variables.variable1]"
    java --version
    mvn --version
  displayName: 'Variables Demo'

- script: whoami
  displayName: Agent identity